create table STATION(
    STATION_ID INTEGER NOT NULL primary key,
    STATION_NAME VARCHAR(50) NOT NULL,
    BIRTHDATE DATE,
    FORMALIZED_DATETIME timestamp(3),
    HOME_COUNT INTEGER,
    WORKING_KILOMETER DECIMAL(4,2)
);

create table TICKET_GATE(
    TICKET_GATE_ID INTEGER NOT NULL primary key,
    TICKET_GATE_NAME VARCHAR(50) NOT NULL,
    STATION_ID INTEGER NOT NULL
);

alter table TICKET_GATE add constraint FK_TICKET_GATE_STATION 
    foreign key (STATION_ID) references STATION (STATION_ID) ;
